# Generated by Django 3.2 on 2023-03-19 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Leagues',
            new_name='League',
        ),
        migrations.RenameField(
            model_name='shirt',
            old_name='leagues',
            new_name='league',
        ),
    ]
