# Generated by Django 3.2 on 2023-04-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20230326_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellShirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, max_length=250, null=True)),
                ('home_away_third', models.CharField(blank=True, max_length=250, null=True)),
                ('league', models.CharField(blank=True, max_length=250, null=True)),
                ('year', models.CharField(blank=True, max_length=250, null=True)),
                ('size', models.CharField(blank=True, max_length=10, null=True)),
                ('condition', models.CharField(blank=True, max_length=250, null=True)),
                ('additional_info', models.TextField()),
                ('image_front', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_back', models.ImageField(blank=True, null=True, upload_to='')),
                ('full_name', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.CharField(blank=True, max_length=250, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
