# Generated by Django 3.2 on 2023-04-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_sellshirt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellshirt',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellshirt',
            name='condition',
            field=models.CharField(default='New', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellshirt',
            name='email',
            field=models.CharField(default='placeholder@email.com', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellshirt',
            name='full_name',
            field=models.CharField(default='John Smith', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellshirt',
            name='home_away_third',
            field=models.CharField(default='Home', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellshirt',
            name='image_back',
            field=models.ImageField(default='test.jpg', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellshirt',
            name='image_front',
            field=models.ImageField(default='test.jpg', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellshirt',
            name='league',
            field=models.CharField(default='Other', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellshirt',
            name='phone_number',
            field=models.CharField(default='00000000', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellshirt',
            name='size',
            field=models.CharField(default='M', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellshirt',
            name='team_name',
            field=models.CharField(default='Club or Nation', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellshirt',
            name='year',
            field=models.CharField(default='0000', max_length=250),
            preserve_default=False,
        ),
    ]
